Update GitHub templates
NEO-TAT/tat_flutter pull request #201
Opened 2023-09-08 15:43 UTC by chenghsuanho

## Description

This PR updates the pull request template and both the bug and feature request issue templates. The updated version improves guidance and is more suitable to our project.

Related to #192.

## How to Verify?

This is not testable until merged. However, one can create a new repository and apply these templates and try them out.

## Screenshots/GIF/Test Results (Optional)

None.

2023-09-09 07:32 UTC, ntut-xuan commented on .github/ISSUE_TEMPLATE/feature_request.md
> +If you have any ideas on how this feature could be implemented, describe them here.
我認為如果要提出 Proposed Implementation，可能會先需要自己做一次 PoC

除了敘述，可以嘗試加上：
- [ ] The purpose has been proved by concept. (POC)

2023-09-15 14:00 UTC, chenghsuanho commented on .github/ISSUE_TEMPLATE/feature_request.md
> +If you have any ideas on how this feature could be implemented, describe them here.
請看看 f9696b2 有沒有達成要求 PoC 的作用

2023-10-21 17:59 UTC, ntut-xuan reviewed
針對於 PR 的部分，我認為可以用以下的框架來描述 PR 的部分

 - Related Issue
 - Description (To describe how the PR work to solve the issue)
 - Implementation (What things the author do)
 - How to Review & Manual Test (How to review the PR and the stories to test the PR)
 - Note (Optional)

舉個例子：

## Description

Related Issue: #999

這個 PR 主要處理了羊駝爆發的問題，我們透過適當的函數調整來控制羊駝的產生數量，並使羊駝的數量不會快速增長。

## Implementation

 - [x] 對於函數進行適當的調整，來控制羊駝的產生數量
 - [x] 對於資料庫的 Schema 進行修改（附上 Schema 的 Patch Script）

# How to Review & Manual Test
 - [x] 測試羊駝在啟動時所產生的數量不會有大爆發的趨勢。
 - [x] 長時間測試羊駝的產生數量是否趨近於平穩。

# Note 
 - [Patch Schema](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

2023-10-22 06:37 UTC, chenghsuanho commented
沒問題，我在 [a633db0](https://github.com/NEO-TAT/tat_flutter/pull/201/commits/a633db093cfdf14812809a7c53aebcbe2310656b) 根據你的範例更新 PR template 了。

2023-10-23 02:23 UTC, ntut-xuan requested changes

2023-10-23 02:23 UTC, ntut-xuan commented on .github/pull_request_template.md
> +- List down manual tests that need to be performed to validate the changes.
建議使用 checklist 的方式，用於在 PR 上瞭解哪些事情已經被完成。

2023-10-23 02:23 UTC, ntut-xuan commented on .github/pull_request_template.md
> +- Mention any breaking changes.
建議使用 checklist 的方式，用於在 PR 上瞭解哪些事情已經被完成。

2023-10-23 03:29 UTC, chenghsuanho commented on .github/pull_request_template.md
> +- List down manual tests that need to be performed to validate the changes.
這個部分據我所知是指導 Reviewer 驗證問題的步驟，為什麼會需要標記是否完成呢？

2023-10-23 03:32 UTC, ntut-xuan commented on .github/pull_request_template.md
> +- List down manual tests that need to be performed to validate the changes.
在寫 PR 的當下除了 Reviewer 要確認一下，自己也要確認一下能否符合上面寫的步驟是否正常。

我們會讓 Reviewer 重複驗證僅僅只是要確保不會發生 ![](https://camo.githubusercontent.com/09cf8868aaf2bdb7f710ca9d04e8970961030305249923e5dde8ad8a8c387e84/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6e696b6b752f776f726b732d6f6e2d6d792d6d616368696e654076302e322e302f62616467652e737667) 的問題。

2023-10-23 03:42 UTC, chenghsuanho commented on .github/pull_request_template.md
> +- List down manual tests that need to be performed to validate the changes.
沒問題，在 de9ee2f 改好了。

2023-10-23 03:42 UTC, chenghsuanho commented on .github/pull_request_template.md
> +- Mention any breaking changes.
沒問題，在 de9ee2f 改好了。

2023-10-23 03:47 UTC, ntut-xuan approved these changes

2023-10-23 03:55 UTC, merged