回復「修課人數」並且新增「學生清單」標題
NEO-TAT/tat_flutter pull request #233
Opened 2024-03-04 05:51 UTC by ntut-xuan

## Description

在這個 PR 中，我回復了修課人數並且新增學生清單標題。

<img width="311" alt="image" src="https://github.com/NEO-TAT/tat_flutter/assets/69747731/13e5c8d6-e9a6-4ea7-9fa0-7011a5038365">

用於顯示目前的修課人數，並且回復學生清單的標題，並在兩個不同的列表中插一個新行來進行區隔。

## How to review it

 - [x] 確認畫面正常顯示無誤。

2024-03-06 06:27 UTC, James-Lu-none requested changes

2024-03-06 06:27 UTC, James-Lu-none commented on lib/ui/pages/coursedetail/screen/course_info_page.dart
> +
consider using final

2025-01-31 07:30 UTC, rileychh commented on lib/ui/pages/coursedetail/screen/course_info_page.dart
> +
Done in de73778f1c5ad428466465e60ed75a5ac33c4327.

2025-01-31 07:54 UTC, rileychh approved these changes
This builds and works well on my Pixel 7.
![Works on my machine](https://img.shields.io/badge/works-on_my_machine-dark_green
)

2025-01-31 07:57 UTC, merged